HEX = _{ 'a'..'f' | '0'..'9' }
ILLEGAL = _{ "\\" | "<" | ">" | "(" | ")" | "[" | "]" }
ESCAPED = _{ "\\" ~ ILLEGAL }
CHAR = _{ (!ILLEGAL ~ ASCII) | ESCAPED }

document = { (rem ~ ("\n" | &EOI))* }
	rem = { "<" ~ id ~ (" " | "\n") ~ content+ ~ ">" }
		id = { HEX{8} }
		content = { text | closure }
			text = { CHAR+ }
			closure = { "(" ~ group ~ ")[" ~ text ~ "]" }
				group = { ASCII_ALPHA_UPPER+ }