name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs: 
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo build
        run: cargo build --verbose
      - name: cargo test
        run: cargo test --verbose
      - name: cargo publish --dry-run
        run: cargo publish --dry-run --verbose